"""Generate docs/rules.md, the packaged catalogue copy and the README rule list,
and for each profile in profiles/ its packaged copy, its docs page
(docs/profiles/ID.md) and its mapping table in docs/profiles.md.

rules/catalogue.yaml and profiles/*.yaml are the source of truth. Profile
rules are documented on their own pages, never in docs/rules.md. Run from the
repository root:

    python scripts/render_rules.py          # write the generated files
    python scripts/render_rules.py --check  # fail if any is out of date
"""

import argparse
import sys
from collections import Counter
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from gff3_validator.profiles import parse_profile  # noqa: E402
from gff3_validator.rules import load_catalogue  # noqa: E402

SOURCE = ROOT / "rules" / "catalogue.yaml"
PACKAGED = ROOT / "gff3_validator" / "catalogue.yaml"
DOCS = ROOT / "docs" / "rules.md"
README = ROOT / "README.md"
START = "<!-- implemented-rules:start (generated by scripts/render_rules.py; do not edit) -->"
END = "<!-- implemented-rules:end -->"
PROFILES = ROOT / "profiles"
PROFILES_PACKAGED = ROOT / "gff3_validator" / "profiles"
PROFILE_DOCS = ROOT / "docs" / "profiles"
PROFILES_MD = ROOT / "docs" / "profiles.md"
MAPPING_START = (
    "<!-- profile-mapping:{id}:start (generated by scripts/render_rules.py; "
    "do not edit) -->"
)
MAPPING_END = "<!-- profile-mapping:{id}:end -->"

CATEGORIES = (
    ("GFF-SYN", "Syntax: file, lines and columns 1 to 8"),
    ("GFF-ATT", "Attributes (column 9)"),
    ("GFF-DIR", "Directives"),
    ("GFF-STR", "Structure: IDs, references and bounds"),
    ("SO", "Sequence Ontology"),
    ("BIO", "Biology (optional, with --genome)"),
    ("HDR", "FHGFF3 header (optional, FAIR-bioHeaders)"),
)


def block(text):
    shown = text.replace("\t", "→").replace("\r", "<CR>")
    return ["```text", *shown.split("\n"), "```"]


def render_docs(catalogue):
    rules = list(catalogue)
    out = [
        "# GFF3 validator rule catalogue",
        "",
        "<!-- Generated from rules/catalogue.yaml by scripts/render_rules.py; do not edit. -->",
        "",
        f"**Catalogue version {catalogue.version}. Draft under review with the "
        "Sequence Ontology group "
        "([FHR-Specification #62](https://github.com/FAIR-bioHeaders/FHR-Specification/issues/62)).** "
        "Rule ids may still change before the first release. Open questions are "
        "collected in [questions-for-SO.md](questions-for-SO.md).",
        "",
        "Levels: **error** (the file violates GFF3 1.26 or the layer's "
        "requirement), **warning** (probably wrong, or a specification "
        "recommendation), **info** (worth knowing; never affects validity). "
        "Layers: `core` (GFF3 syntax and structure), `so` (Sequence Ontology), "
        "`biology` (optional, needs `--genome`), `fhgff3` (optional "
        "FAIR-bioHeaders header). A suggested fix is guidance; the validator "
        "never rewrites a file. In examples, `→` stands for a tab. Rules of "
        "repository and community profiles (for example `AGB-*`) are not part "
        "of this catalogue; see [profiles.md](profiles.md).",
        "",
        "Sources:",
        "",
    ]
    for key, source in catalogue.sources.items():
        out.append(f"- `{key}`: [{source['title']}]({source['url']})")
    out += [
        "",
        "## Summary",
        "",
        "| Category | Rules | Implemented | Planned | Need SO input |",
        "|---|---|---|---|---|",
    ]
    for prefix, title in CATEGORIES:
        group = [rule for rule in rules if rule.category == prefix]
        status = Counter(rule.status for rule in group)
        needs = sum(rule.needs_so for rule in group)
        out.append(
            f"| [{prefix}](#{prefix.lower()}) {title} | {len(group)} | "
            f"{status['implemented']} | {status['planned']} | {needs} |"
        )
    status = Counter(rule.status for rule in rules)
    out.append(
        f"| **Total** | {len(rules)} | {status['implemented']} | "
        f"{status['planned']} | {sum(rule.needs_so for rule in rules)} |"
    )
    for prefix, title in CATEGORIES:
        out += ["", f"## {prefix}", "", title, ""]
        out += ["| Id | Level | Status | Title |", "|---|---|---|---|"]
        group = [rule for rule in rules if rule.category == prefix]
        for rule in group:
            title_cell = rule.title.replace("|", "\\|")
            out.append(
                f"| [{rule.id}](#{rule.id.lower()}) | {rule.level} | "
                f"{rule.status} | {title_cell} |"
            )
        for rule in group:
            reference = rule.reference
            out += [
                "",
                f"### {rule.id}",
                "",
                f"**{rule.title}**",
                "",
                f"- Level: {rule.level}; layer: {rule.layer}; status: "
                f"{rule.status}; review: {rule.review}"
                + ("; **needs SO input**" if rule.needs_so else ""),
                f"- Reference: [{reference['section']}]"
                f"({catalogue.reference_url(rule)}) ({reference['source']})",
                "",
                rule.description,
                "",
                "Example (invalid):",
                "",
                *block(rule.example),
            ]
            if rule.valid:
                out += ["", "Valid:", "", *block(rule.valid)]
            out += ["", f"Fix: {rule.fix}"]
            if rule.notes:
                out += ["", f"Notes: {rule.notes}"]
    return "\n".join(out) + "\n"


def render_readme(catalogue, readme):
    head, rest = readme.split(START, 1)
    _, tail = rest.split(END, 1)
    implemented = catalogue.implemented()
    lines = [
        f"{len(implemented)} of {len(catalogue.rules)} catalogue rules are "
        "implemented:",
        "",
    ]
    for rule in implemented:
        lines.append(f"- `{rule.id}` ({rule.level}): {rule.title}")
    return head + START + "\n" + "\n".join(lines) + "\n" + END + tail


def cell(text):
    return " ".join(str(text).split()).replace("|", "\\|")


def profile_link(profile, reference):
    return f"[{cell(reference['section'])}]({profile.reference_url(reference)})"


def rule_link(rule_id, profile):
    if rule_id in profile.rules:
        return f"[{rule_id}](profiles/{profile.id}.md#{rule_id.lower()})"
    return f"[{rule_id}](rules.md#{rule_id.lower()})"


def render_profile_docs(profile, catalogue):
    source = profile.source
    rules = list(profile)
    out = [
        f"# {profile.name} profile (`{profile.id}`)",
        "",
        f"<!-- Generated from profiles/{profile.id}.yaml by scripts/render_rules.py; "
        "do not edit. -->",
        "",
        f"**Profile version {profile.version}; {profile.review}.** Use it with "
        f"`gff3-validate --profile {profile.id}`. See [profiles.md](../profiles.md) "
        "for how profiles work and how they are reported.",
        "",
        " ".join(profile.description.split()),
        "",
        f"- Source: [{source['title']}]({source['url']})",
        f"- License of the source: {source['license']}",
    ]
    if source.get("commit") or source.get("date"):
        out.append(
            "- Version of the source: "
            + ", ".join(
                part
                for part in (
                    source.get("commit") and f"commit {source['commit']}",
                    source.get("date"),
                )
                if part
            )
        )
    out += [
        f"- Rule ids: `{profile.prefix}-NNN`",
        "",
        "Profile findings are reported apart from the core findings and never "
        "change whether a file is valid GFF3. A file complies with the profile "
        "when it is valid GFF3 and has no profile errors.",
        "",
        "## Summary",
        "",
        "| Id | Level | Status | Title |",
        "|---|---|---|---|",
    ]
    for rule in rules:
        out.append(
            f"| [{rule.id}](#{rule.id.lower()}) | {rule.level} | {rule.status} | "
            f"{cell(rule.title)} |"
        )
    if profile.levels:
        out += [
            "",
            "## Core rules with a raised level",
            "",
            "The core finding keeps its catalogue level; the profile reports it "
            "again at the raised level.",
            "",
            "| Rule | Catalogue level | Profile level | Source | Reason |",
            "|---|---|---|---|---|",
        ]
        for rule_id, change in profile.levels.items():
            out.append(
                f"| [{rule_id}](../rules.md#{rule_id.lower()}) | "
                f"{catalogue[rule_id].level} | {change.level} | "
                f"{profile_link(profile, change.reference)} | {cell(change.reason)} |"
            )
    out += ["", "## Rules"]
    for rule in rules:
        out += [
            "",
            f"### {rule.id}",
            "",
            f"**{rule.title}**",
            "",
            f"- Level: {rule.level}; status: {rule.status}",
            f"- Reference: {profile_link(profile, rule.reference)}",
            "",
            " ".join(rule.description.split()),
            "",
            "Example (not compliant):",
            "",
            *block(rule.example),
        ]
        if rule.valid:
            out += ["", "Compliant:", "", *block(rule.valid)]
        out += ["", f"Fix: {rule.fix}"]
        if rule.notes:
            out += ["", f"Notes: {' '.join(rule.notes.split())}"]
    if profile.guidance:
        out += [
            "",
            "## Guidance, not checked by profile rules",
            "",
            "| Source | Recommendation | Covered by | Why no profile rule |",
            "|---|---|---|---|",
        ]
        for item in profile.guidance:
            covered = ", ".join(
                rule_link(rule_id, profile)
                .replace("(rules.md", "(../rules.md")
                .replace(f"(profiles/{profile.id}.md", "(")
                for rule_id in item.covered_by
            )
            out.append(
                f"| {profile_link(profile, item.reference)} | "
                f"{cell(item.recommendation)} | {covered or 'nothing'} | "
                f"{cell(item.reason)} |"
            )
    return "\n".join(out) + "\n"


def render_mapping(profile, catalogue):
    """The recommendation -> rule or guidance table for docs/profiles.md, in
    the order of the source's sections (as the guidance lists them)."""
    rows = {}
    order = []

    def add(anchor, row):
        if anchor not in rows:
            rows[anchor] = []
            order.append(anchor)
        rows[anchor].append(row)

    for item in profile.guidance:
        rows.setdefault(item.reference.get("anchor", ""), [])
        if item.reference.get("anchor", "") not in order:
            order.append(item.reference.get("anchor", ""))
    for rule_id, change in profile.levels.items():
        add(
            change.reference.get("anchor", ""),
            (
                0,
                profile_link(profile, change.reference),
                f"{rule_link(rule_id, profile)} raised to {change.level}",
                cell(
                    f"{catalogue[rule_id].title} (core level "
                    f"{catalogue[rule_id].level})"
                ),
            ),
        )
    for rule in profile:
        add(
            rule.reference.get("anchor", ""),
            (
                1,
                profile_link(profile, rule.reference),
                f"{rule_link(rule.id, profile)} ({rule.level})",
                cell(rule.title),
            ),
        )
    for item in profile.guidance:
        covered = ", ".join(rule_link(r, profile) for r in item.covered_by)
        add(
            item.reference.get("anchor", ""),
            (
                2,
                profile_link(profile, item.reference),
                "guidance, not checked"
                + (f" (core or profile rules: {covered})" if covered else ""),
                cell(item.recommendation),
            ),
        )
    lines = [
        f"{profile.name} {profile.version}: {len(profile.implemented())} profile "
        f"rules, {len(profile.levels)} raised core rules and "
        f"{len(profile.guidance)} recommendations kept as guidance.",
        "",
        "| Recommendation (source section) | Checked by | What |",
        "|---|---|---|",
    ]
    for anchor in order:
        for _, section, checked, what in sorted(rows[anchor], key=lambda r: r[0]):
            lines.append(f"| {section} | {checked} | {what} |")
    return "\n".join(lines)


def render_profiles_md(text, profile, catalogue):
    start = MAPPING_START.format(id=profile.id)
    end = MAPPING_END.format(id=profile.id)
    head, rest = text.split(start, 1)
    _, tail = rest.split(end, 1)
    return head + start + "\n" + render_mapping(profile, catalogue) + "\n" + end + tail


def profile_outputs(catalogue):
    expected = {}
    profiles_md = PROFILES_MD.read_bytes().decode("utf-8")
    for path in sorted(PROFILES.glob("*.yaml")):
        text = path.read_bytes().decode("utf-8")
        profile = parse_profile(text, catalogue)
        if profile.id != path.stem:
            raise SystemExit(f"{path}: id {profile.id} does not match the file name")
        expected[PROFILES_PACKAGED / path.name] = text
        expected[PROFILE_DOCS / f"{profile.id}.md"] = render_profile_docs(
            profile, catalogue
        )
        profiles_md = render_profiles_md(profiles_md, profile, catalogue)
    expected[PROFILES_MD] = profiles_md
    return expected


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true", help="only check for drift")
    args = parser.parse_args(argv)
    source = SOURCE.read_bytes().decode("utf-8")
    catalogue = load_catalogue(SOURCE)
    expected = {
        PACKAGED: source,
        DOCS: render_docs(catalogue),
        README: render_readme(catalogue, README.read_bytes().decode("utf-8")),
    }
    expected.update(profile_outputs(catalogue))
    packaged = {
        path for path in PROFILES_PACKAGED.glob("*.yaml") if path not in expected
    }
    stale = [
        path
        for path, text in expected.items()
        if not path.exists() or path.read_bytes() != text.encode("utf-8")
    ]
    if args.check:
        for path in stale:
            print(f"out of date: {path.relative_to(ROOT)}", file=sys.stderr)
        for path in sorted(packaged):
            print(f"no source profile: {path.relative_to(ROOT)}", file=sys.stderr)
        if stale or packaged:
            print("run: python scripts/render_rules.py", file=sys.stderr)
            return 1
        return 0
    for path in stale:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(expected[path].encode("utf-8"))
        print(f"wrote {path.relative_to(ROOT)}")
    for path in sorted(packaged):
        path.unlink()
        print(f"removed {path.relative_to(ROOT)} (no source profile)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
