"""Generate docs/rules.md, the packaged catalogue copy and the README rule list.

rules/catalogue.yaml is the source of truth. Run from the repository root:

    python scripts/render_rules.py          # write the generated files
    python scripts/render_rules.py --check  # fail if any is out of date
"""

import argparse
import sys
from collections import Counter
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from gff3_validator.rules import load_catalogue  # noqa: E402

SOURCE = ROOT / "rules" / "catalogue.yaml"
PACKAGED = ROOT / "gff3_validator" / "catalogue.yaml"
DOCS = ROOT / "docs" / "rules.md"
README = ROOT / "README.md"
START = "<!-- implemented-rules:start (generated by scripts/render_rules.py; do not edit) -->"
END = "<!-- implemented-rules:end -->"

CATEGORIES = (
    ("GFF-SYN", "Syntax: file, lines and columns 1 to 8"),
    ("GFF-ATT", "Attributes (column 9)"),
    ("GFF-DIR", "Directives"),
    ("GFF-STR", "Structure: IDs, references and bounds"),
    ("SO", "Sequence Ontology"),
    ("BIO", "Biology (optional, with --genome)"),
    ("HDR", "FHGFF3 header (optional, FAIR-bioHeaders)"),
)


def block(text):
    shown = text.replace("\t", "→").replace("\r", "<CR>")
    return ["```text", *shown.split("\n"), "```"]


def render_docs(catalogue):
    rules = list(catalogue)
    out = [
        "# GFF3 validator rule catalogue",
        "",
        "<!-- Generated from rules/catalogue.yaml by scripts/render_rules.py; do not edit. -->",
        "",
        f"**Catalogue version {catalogue.version}. Draft under review with the "
        "Sequence Ontology group "
        "([FHR-Specification #62](https://github.com/FAIR-bioHeaders/FHR-Specification/issues/62)).** "
        "Rule ids may still change before the first release. Open questions are "
        "collected in [questions-for-SO.md](questions-for-SO.md).",
        "",
        "Levels: **error** (the file violates GFF3 1.26 or the layer's "
        "requirement), **warning** (probably wrong, or a specification "
        "recommendation), **info** (worth knowing; never affects validity). "
        "Layers: `core` (GFF3 syntax and structure), `so` (Sequence Ontology), "
        "`biology` (optional, needs `--genome`), `fhgff3` (optional "
        "FAIR-bioHeaders header). A suggested fix is guidance; the validator "
        "never rewrites a file. In examples, `→` stands for a tab.",
        "",
        "Sources:",
        "",
    ]
    for key, source in catalogue.sources.items():
        out.append(f"- `{key}`: [{source['title']}]({source['url']})")
    out += [
        "",
        "## Summary",
        "",
        "| Category | Rules | Implemented | Planned | Need SO input |",
        "|---|---|---|---|---|",
    ]
    for prefix, title in CATEGORIES:
        group = [rule for rule in rules if rule.category == prefix]
        status = Counter(rule.status for rule in group)
        needs = sum(rule.needs_so for rule in group)
        out.append(
            f"| [{prefix}](#{prefix.lower()}) {title} | {len(group)} | "
            f"{status['implemented']} | {status['planned']} | {needs} |"
        )
    status = Counter(rule.status for rule in rules)
    out.append(
        f"| **Total** | {len(rules)} | {status['implemented']} | "
        f"{status['planned']} | {sum(rule.needs_so for rule in rules)} |"
    )
    for prefix, title in CATEGORIES:
        out += ["", f"## {prefix}", "", title, ""]
        out += ["| Id | Level | Status | Title |", "|---|---|---|---|"]
        group = [rule for rule in rules if rule.category == prefix]
        for rule in group:
            title_cell = rule.title.replace("|", "\\|")
            out.append(
                f"| [{rule.id}](#{rule.id.lower()}) | {rule.level} | "
                f"{rule.status} | {title_cell} |"
            )
        for rule in group:
            reference = rule.reference
            out += [
                "",
                f"### {rule.id}",
                "",
                f"**{rule.title}**",
                "",
                f"- Level: {rule.level}; layer: {rule.layer}; status: "
                f"{rule.status}; review: {rule.review}"
                + ("; **needs SO input**" if rule.needs_so else ""),
                f"- Reference: [{reference['section']}]"
                f"({catalogue.reference_url(rule)}) ({reference['source']})",
                "",
                rule.description,
                "",
                "Example (invalid):",
                "",
                *block(rule.example),
            ]
            if rule.valid:
                out += ["", "Valid:", "", *block(rule.valid)]
            out += ["", f"Fix: {rule.fix}"]
            if rule.notes:
                out += ["", f"Notes: {rule.notes}"]
    return "\n".join(out) + "\n"


def render_readme(catalogue, readme):
    head, rest = readme.split(START, 1)
    _, tail = rest.split(END, 1)
    implemented = catalogue.implemented()
    lines = [
        f"{len(implemented)} of {len(catalogue.rules)} catalogue rules are "
        "implemented:",
        "",
    ]
    for rule in implemented:
        lines.append(f"- `{rule.id}` ({rule.level}): {rule.title}")
    return head + START + "\n" + "\n".join(lines) + "\n" + END + tail


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true", help="only check for drift")
    args = parser.parse_args(argv)
    source = SOURCE.read_bytes().decode("utf-8")
    catalogue = load_catalogue(SOURCE)
    expected = {
        PACKAGED: source,
        DOCS: render_docs(catalogue),
        README: render_readme(catalogue, README.read_bytes().decode("utf-8")),
    }
    stale = [
        path
        for path, text in expected.items()
        if not path.exists() or path.read_bytes() != text.encode("utf-8")
    ]
    if args.check:
        for path in stale:
            print(f"out of date: {path.relative_to(ROOT)}", file=sys.stderr)
        if stale:
            print("run: python scripts/render_rules.py", file=sys.stderr)
            return 1
        return 0
    for path in stale:
        path.write_bytes(expected[path].encode("utf-8"))
        print(f"wrote {path.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
